import duckdb
from edgar.curate.mapping import CANONICAL_FIELDS

FIELD_DEFINITIONS: dict[str, str] = {
    "revenue": "Total revenue recognized in the period from contracts with "
               "customers. Duration fact.",
    "cost_of_revenue": "Direct cost attributable to goods and services sold "
                       "in the period. Often not separately disclosed. "
                       "Duration fact.",
    "gross_profit": "Revenue less cost of revenue. Duration fact. Reported "
                    "directly when available; not derived in v1.",
    "operating_income": "Profit from operations before interest and tax. "
                        "Duration fact.",
    "net_income": "Profit after all expenses, interest, and tax, attributable "
                  "to the parent entity. Duration fact.",
    "total_assets": "Total assets held at the balance sheet date. Instant fact.",
    "total_liabilities": "Total obligations owed at the balance sheet date. "
                         "Instant fact.",
    "stockholders_equity": "Residual interest in assets after deducting "
                           "liabilities. Instant fact.",
    "operating_cash_flow": "Net cash generated by operating activities in the "
                           "period. Duration fact.",
    "capex": "Cash paid to acquire property, plant, and equipment in the "
             "period, normalized to a positive magnitude. Duration fact.",
}

_TABLES = ("fact", "company", "mapping_rule")


def generate_data_dictionary(con: duckdb.DuckDBPyConnection) -> str:
    lines = [
        "# Data Dictionary",
        "",
        "Generated from the live schema. Do not edit by hand — "
        "regenerate with `python -m edgar.quality.dictionary`.",
        "",
        "## Canonical fields",
        "",
        "| Field | Definition |",
        "|---|---|",
    ]
    for f in CANONICAL_FIELDS:
        lines.append(f"| `{f}` | {FIELD_DEFINITIONS[f]} |")

    for table in _TABLES:
        cols = con.execute(
            "SELECT column_name, data_type FROM information_schema.columns "
            "WHERE table_name = ? ORDER BY ordinal_position", [table]
        ).fetchall()
        if not cols:
            continue
        lines += ["", f"## {table}", "", "| Column | Type |", "|---|---|"]
        lines += [f"| `{c}` | {t} |" for c, t in cols]

    rules = con.execute(
        "SELECT canonical_field, source_tag, priority, rationale "
        "FROM mapping_rule ORDER BY canonical_field, priority"
    ).fetchall()
    if rules:
        lines += ["", "## Mapping rules", "",
                  "| Canonical field | Source tag | Priority | Rationale |",
                  "|---|---|---|---|"]
        lines += [f"| `{f}` | `{t}` | {p} | {r} |" for f, t, p, r in rules]

    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    from pathlib import Path
    from edgar.db import connect
    from edgar.config import get_settings
    out = Path("docs/data-dictionary.md")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(generate_data_dictionary(connect(get_settings().duckdb_path)))
    print(f"wrote {out}")
